version: 1.2
workflows:
- name: Regenotype
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Regenotype.wdl
  testParameterFiles:
- name: Standardize
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SVTK.wdl
  testParameterFiles: