version: 1.2
workflows:
- name: Regenotype
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Regenotype.wdl
  testParameterFiles:
- name: Standardize
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Standardize.wdl
  testParameterFiles:
- name: Sv2Igv
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Sv2Igv.wdl
  testParameterFiles:
- name: JediGraph
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/JediGraph.wdl
  testParameterFiles:
- name: Trgt
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/Trgt.wdl
  testParameterFiles: